// <auto-generated />
namespace MyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _222222 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_222222));
        
        string IMigrationMetadata.Id
        {
            get { return "201405011756452_222222"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
