// <auto-generated />
namespace MyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _14789788 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_14789788));
        
        string IMigrationMetadata.Id
        {
            get { return "201405031718597_14789788"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
