// <auto-generated />
namespace MyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _13Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_13Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201404011644536_13Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
